language: php         # 声明构建语言环境

php:
  - "8.0"

notifications:        # 每次构建的时候是否邮箱通知
  email: true

sudo: false           # sudo 权限

branches:             # 部署分支
  only:
    - main

cache:                # 缓存
  directories:
    - $HOME/.composer/cache

before_install:       # 安装前操作
  - chmod -Rf 777 runtime  # 改变访问权限
  - composer self-update

install:              # 安装
  - composer install --no-dev --no-interaction --ignore-platform-reqs
  - zip -r --exclude='*.git*' --exclude='*.zip' --exclude='*.travis.yml' tp8admin.zip .

script:               # 执行:下面的命令
  - php think command:getPhpVersion

# 打包，参考文档：https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # 填写 GitHub 的 token （Settings -> Developer Settings -> Personal access tokens->tokens (classic)）
  file: "tp8admin.zip"
  skip_cleanup: true
  on:
    tags: true
